### ISSUE TITLE
no module named python-pylint-common

### ISSUE THREAD

**Issue by MalikRumi** [landscapeio/pylint-common#3]
Ubuntu 16.04, Python 2.7.10
I read https://github.com/landscapeio/prospector/issues/18
I just installed pylint, python-pylint-django, and python-pylint-common at the same time from app grid. I did the tutorial on the documentation page. I created a conf file (with some difficulty until I found it in the docs) which included:

```
# List of plugins (as comma separated values of python modules names) to load,
# usually to register additional checkers.
load-plugins=python-pylint-common, python-pylint-django
```

```
malikarumi@Tetuoan2:~/Projects$ pylint new_models.py
Traceback (most recent call last):
  File "/usr/bin/pylint", line 3, in <module>
    run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 1280, in __init__
    linter.load_plugin_modules(plugins)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 485, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/usr/lib/python2.7/dist-packages/astroid/modutils.py", line 186, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/usr/lib/python2.7/dist-packages/astroid/modutils.py", line 228, in load_module_from_modpath
    mp_file, mp_filename, mp_desc = imp.find_module(part, path)
ImportError: No module named python-pylint-common
malikarumi@Tetuoan2:~/Projects$ grep python-pylint-common


^C
```

grep just gave me a blinking cursor.

I can see that neither of these plugins are in usr/bin/, where I do see pylint. I would have assumed they all went to the same place, but apparently not. What do I do now?

**Comment by patvdleer** [comment]
Should `python-` be in front of it? Mine works fine without it.
```
[MASTER]
load-plugins=pylint_common, pylint_django
```

**Comment by carlio** [comment]
Should be fixed in later versions of prospector by prospector not including this any more.
